on: push
name: on push
jobs:
  UtilsUnitTests:
    name: Unit tests for hudson_utils
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: GitHub Action for pytest
        uses: cclauss/GitHub-Action-for-pytest@master
        with:
          args: pytest  --cov=hudson_utils --cov
  LintAndStyle:
    name: Lint and style check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
      - name: Lint with flake8
        run: |
          make lint_and_format
