on: push
name: on push
jobs:
  LyntStyleAndUnitTests:
    name: Lint and style check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          make lint_and_format
      - name: Unit tests
        run: |
          make run_tests
